from CollectorTool  import CreateData
import argparse

parser = argparse.ArgumentParser(description = '', add_help = False)
parser = argparse.ArgumentParser()

parser.add_argument('-s','--signalFiles', action='store',
    dest='signalFiles', required = True, nargs='+',
    help = "The npz signal files generated by Collector tool")

parser.add_argument('-b','--backgroundFiles', action='store',
    dest='backgroundFiles', required = True, nargs='+',
    help = "The npz background files generated by Collector tool")

parser.add_argument('-o','--outputFiles', action='store',
    dest='outputFiles', required = False, default = None,
    help = "The output store name.")

args = parser.parse_args()
cdata  = CreateData(10)

cdata( args.signalFiles,  args.backgroundFiles, args.outputFiles )
